import { useState, useEffect } from 'react'
import { useNavigate } from 'react-router-dom'
import { ArrowLeft, Calendar, Clock, Users, RefreshCw, Bell, ChefHat, Save } from 'lucide-react'

function MealPlanSettingsPage() {
  const navigate = useNavigate()
  const [settings, setSettings] = useState({
    // Meal Types
    includeBreakfast: true,
    includeLunch: true,
    includeDinner: true,
    includeSnacks: false,
    
    // Default Settings
    defaultServings: '2',
    cookingTime: 'any', // 'quick', 'moderate', 'any'
    skillLevel: 'any', // 'beginner', 'intermediate', 'advanced', 'any'
    
    // Meal Prep
    mealPrepMode: false,
    batchCooking: false,
    leftoverFriendly: true,
    
    // Auto-Generation
    autoGenerate: false,
    autoGenerateDay: 'sunday', // 'sunday', 'monday', etc.
    generateDaysAhead: '7',
    
    // Variety
    repeatMeals: false,
    varietyLevel: 'balanced', // 'low', 'balanced', 'high'
    
    // Budget
    budgetConscious: false,
    maxCostPerMeal: '',
    
    // Notifications
    planReminder: true,
    reminderTime: '18:00',
    shoppingListReminder: true,
    prepReminder: false
  })

  const [saved, setSaved] = useState(false)

  useEffect(() => {
    // Load saved settings
    const savedSettings = localStorage.getItem('mealPlanSettings')
    if (savedSettings) {
      setSettings(JSON.parse(savedSettings))
    }
  }, [])

  const handleChange = (field, value) => {
    setSettings(prev => ({ ...prev, [field]: value }))
    setSaved(false)
  }

  const handleSave = () => {
    localStorage.setItem('mealPlanSettings', JSON.stringify(settings))
    setSaved(true)
    setTimeout(() => setSaved(false), 3000)
  }

  return (
    <div className="min-h-screen bg-gray-50 dark:bg-gray-900 pb-20">
      {/* Header */}
      <header className="bg-white dark:bg-gray-800 shadow-sm sticky top-0 z-10">
        <div className="px-4 py-3 flex items-center gap-3">
          <button
            onClick={() => navigate(-1)}
            className="p-2 hover:bg-gray-100 dark:hover:bg-gray-700 rounded-lg transition-colors"
          >
            <ArrowLeft size={20} className="text-gray-700 dark:text-gray-300" />
          </button>
          <div>
            <h1 className="text-xl font-bold text-gray-900 dark:text-white">Meal Plan Settings</h1>
            <p className="text-xs text-gray-600 dark:text-gray-400">
              Customize your meal planning experience
            </p>
          </div>
        </div>
      </header>

      <div className="max-w-2xl mx-auto px-4 py-6 space-y-6">
        {/* Meal Types */}
        <div className="bg-white dark:bg-gray-800 rounded-xl p-6 shadow-sm">
          <h2 className="text-lg font-bold text-gray-900 dark:text-white mb-4 flex items-center gap-2">
            <Calendar className="text-primary-600" />
            Meal Types to Plan
          </h2>
          <div className="space-y-3">
            {[
              { key: 'includeBreakfast', label: 'Breakfast', emoji: '🍳' },
              { key: 'includeLunch', label: 'Lunch', emoji: '🥙' },
              { key: 'includeDinner', label: 'Dinner', emoji: '🍽️' },
              { key: 'includeSnacks', label: 'Snacks', emoji: '🍿' }
            ].map((meal) => (
              <label
                key={meal.key}
                className="flex items-center gap-3 p-3 bg-gray-50 dark:bg-gray-700 rounded-lg cursor-pointer hover:bg-gray-100 dark:hover:bg-gray-600 transition-colors"
              >
                <input
                  type="checkbox"
                  checked={settings[meal.key]}
                  onChange={(e) => handleChange(meal.key, e.target.checked)}
                  className="w-5 h-5 text-primary-600 rounded focus:ring-2 focus:ring-primary-600"
                />
                <span className="text-2xl">{meal.emoji}</span>
                <span className="font-medium text-gray-900 dark:text-white">{meal.label}</span>
              </label>
            ))}
          </div>
        </div>

        {/* Default Preferences */}
        <div className="bg-white dark:bg-gray-800 rounded-xl p-6 shadow-sm">
          <h2 className="text-lg font-bold text-gray-900 dark:text-white mb-4 flex items-center gap-2">
            <ChefHat className="text-primary-600" />
            Default Preferences
          </h2>
          <div className="space-y-4">
            {/* Default Servings */}
            <div>
              <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-2">
                <Users size={16} className="inline mr-2 text-primary-600" />
                Default Servings
              </label>
              <select
                value={settings.defaultServings}
                onChange={(e) => handleChange('defaultServings', e.target.value)}
                className="w-full px-4 py-2 border border-gray-300 dark:border-gray-600 rounded-lg bg-white dark:bg-gray-900 text-gray-900 dark:text-white focus:ring-2 focus:ring-primary-600"
              >
                <option value="1">1 Person</option>
                <option value="2">2 People</option>
                <option value="4">4 People (Family)</option>
                <option value="6">6+ People</option>
              </select>
            </div>

            {/* Cooking Time Preference */}
            <div>
              <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-2">
                <Clock size={16} className="inline mr-2 text-primary-600" />
                Preferred Cooking Time
              </label>
              <select
                value={settings.cookingTime}
                onChange={(e) => handleChange('cookingTime', e.target.value)}
                className="w-full px-4 py-2 border border-gray-300 dark:border-gray-600 rounded-lg bg-white dark:bg-gray-900 text-gray-900 dark:text-white focus:ring-2 focus:ring-primary-600"
              >
                <option value="any">Any Duration</option>
                <option value="quick">Quick (Under 30 min)</option>
                <option value="moderate">Moderate (30-60 min)</option>
              </select>
            </div>

            {/* Skill Level */}
            <div>
              <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-2">
                Cooking Skill Level
              </label>
              <select
                value={settings.skillLevel}
                onChange={(e) => handleChange('skillLevel', e.target.value)}
                className="w-full px-4 py-2 border border-gray-300 dark:border-gray-600 rounded-lg bg-white dark:bg-gray-900 text-gray-900 dark:text-white focus:ring-2 focus:ring-primary-600"
              >
                <option value="any">Any Level</option>
                <option value="beginner">Beginner Friendly</option>
                <option value="intermediate">Intermediate</option>
                <option value="advanced">Advanced</option>
              </select>
            </div>
          </div>
        </div>

        {/* Meal Prep Options */}
        <div className="bg-white dark:bg-gray-800 rounded-xl p-6 shadow-sm">
          <h2 className="text-lg font-bold text-gray-900 dark:text-white mb-4">
            Meal Prep Preferences
          </h2>
          <div className="space-y-3">
            <label className="flex items-center gap-3 p-3 bg-gray-50 dark:bg-gray-700 rounded-lg cursor-pointer">
              <input
                type="checkbox"
                checked={settings.mealPrepMode}
                onChange={(e) => handleChange('mealPrepMode', e.target.checked)}
                className="w-5 h-5 text-primary-600 rounded focus:ring-2 focus:ring-primary-600"
              />
              <div>
                <p className="font-medium text-gray-900 dark:text-white">Meal Prep Mode</p>
                <p className="text-sm text-gray-600 dark:text-gray-400">Optimize for batch cooking</p>
              </div>
            </label>

            <label className="flex items-center gap-3 p-3 bg-gray-50 dark:bg-gray-700 rounded-lg cursor-pointer">
              <input
                type="checkbox"
                checked={settings.batchCooking}
                onChange={(e) => handleChange('batchCooking', e.target.checked)}
                className="w-5 h-5 text-primary-600 rounded focus:ring-2 focus:ring-primary-600"
              />
              <div>
                <p className="font-medium text-gray-900 dark:text-white">Batch Cooking</p>
                <p className="text-sm text-gray-600 dark:text-gray-400">Recipes that scale well</p>
              </div>
            </label>

            <label className="flex items-center gap-3 p-3 bg-gray-50 dark:bg-gray-700 rounded-lg cursor-pointer">
              <input
                type="checkbox"
                checked={settings.leftoverFriendly}
                onChange={(e) => handleChange('leftoverFriendly', e.target.checked)}
                className="w-5 h-5 text-primary-600 rounded focus:ring-2 focus:ring-primary-600"
              />
              <div>
                <p className="font-medium text-gray-900 dark:text-white">Leftover Friendly</p>
                <p className="text-sm text-gray-600 dark:text-gray-400">Meals that reheat well</p>
              </div>
            </label>
          </div>
        </div>

        {/* Auto-Generation */}
        <div className="bg-white dark:bg-gray-800 rounded-xl p-6 shadow-sm">
          <h2 className="text-lg font-bold text-gray-900 dark:text-white mb-4 flex items-center gap-2">
            <RefreshCw className="text-primary-600" />
            Auto-Generate Plans
          </h2>
          
          <label className="flex items-center gap-3 p-3 bg-gray-50 dark:bg-gray-700 rounded-lg cursor-pointer mb-4">
            <input
              type="checkbox"
              checked={settings.autoGenerate}
              onChange={(e) => handleChange('autoGenerate', e.target.checked)}
              className="w-5 h-5 text-primary-600 rounded focus:ring-2 focus:ring-primary-600"
            />
            <div>
              <p className="font-medium text-gray-900 dark:text-white">Enable Auto-Generate</p>
              <p className="text-sm text-gray-600 dark:text-gray-400">Automatically create weekly meal plans</p>
            </div>
          </label>

          {settings.autoGenerate && (
            <div className="space-y-4 mt-4 pl-8">
              <div>
                <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-2">
                  Generate On
                </label>
                <select
                  value={settings.autoGenerateDay}
                  onChange={(e) => handleChange('autoGenerateDay', e.target.value)}
                  className="w-full px-4 py-2 border border-gray-300 dark:border-gray-600 rounded-lg bg-white dark:bg-gray-900 text-gray-900 dark:text-white focus:ring-2 focus:ring-primary-600"
                >
                  <option value="sunday">Sunday</option>
                  <option value="monday">Monday</option>
                  <option value="tuesday">Tuesday</option>
                  <option value="wednesday">Wednesday</option>
                  <option value="thursday">Thursday</option>
                  <option value="friday">Friday</option>
                  <option value="saturday">Saturday</option>
                </select>
              </div>

              <div>
                <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-2">
                  Plan Duration
                </label>
                <select
                  value={settings.generateDaysAhead}
                  onChange={(e) => handleChange('generateDaysAhead', e.target.value)}
                  className="w-full px-4 py-2 border border-gray-300 dark:border-gray-600 rounded-lg bg-white dark:bg-gray-900 text-gray-900 dark:text-white focus:ring-2 focus:ring-primary-600"
                >
                  <option value="3">3 Days</option>
                  <option value="7">1 Week</option>
                  <option value="14">2 Weeks</option>
                </select>
              </div>
            </div>
          )}
        </div>

        {/* Variety */}
        <div className="bg-white dark:bg-gray-800 rounded-xl p-6 shadow-sm">
          <h2 className="text-lg font-bold text-gray-900 dark:text-white mb-4">
            Meal Variety
          </h2>
          
          <label className="flex items-center gap-3 p-3 bg-gray-50 dark:bg-gray-700 rounded-lg cursor-pointer mb-4">
            <input
              type="checkbox"
              checked={settings.repeatMeals}
              onChange={(e) => handleChange('repeatMeals', e.target.checked)}
              className="w-5 h-5 text-primary-600 rounded focus:ring-2 focus:ring-primary-600"
            />
            <div>
              <p className="font-medium text-gray-900 dark:text-white">Allow Repeat Meals</p>
              <p className="text-sm text-gray-600 dark:text-gray-400">Same meals can appear multiple times per week</p>
            </div>
          </label>

          <div>
            <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-2">
              Variety Level
            </label>
            <select
              value={settings.varietyLevel}
              onChange={(e) => handleChange('varietyLevel', e.target.value)}
              className="w-full px-4 py-2 border border-gray-300 dark:border-gray-600 rounded-lg bg-white dark:bg-gray-900 text-gray-900 dark:text-white focus:ring-2 focus:ring-primary-600"
            >
              <option value="low">Low (Familiar favorites)</option>
              <option value="balanced">Balanced (Mix of new and familiar)</option>
              <option value="high">High (Try new things)</option>
            </select>
          </div>
        </div>

        {/* Budget */}
        <div className="bg-white dark:bg-gray-800 rounded-xl p-6 shadow-sm">
          <h2 className="text-lg font-bold text-gray-900 dark:text-white mb-4">
            Budget Settings
          </h2>
          
          <label className="flex items-center gap-3 p-3 bg-gray-50 dark:bg-gray-700 rounded-lg cursor-pointer mb-4">
            <input
              type="checkbox"
              checked={settings.budgetConscious}
              onChange={(e) => handleChange('budgetConscious', e.target.checked)}
              className="w-5 h-5 text-primary-600 rounded focus:ring-2 focus:ring-primary-600"
            />
            <div>
              <p className="font-medium text-gray-900 dark:text-white">Budget-Conscious Planning</p>
              <p className="text-sm text-gray-600 dark:text-gray-400">Prioritize affordable meals</p>
            </div>
          </label>

          {settings.budgetConscious && (
            <div className="pl-8">
              <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-2">
                Max Cost Per Meal (Optional)
              </label>
              <input
                type="number"
                value={settings.maxCostPerMeal}
                onChange={(e) => handleChange('maxCostPerMeal', e.target.value)}
                placeholder="15.00"
                className="w-full px-4 py-2 border border-gray-300 dark:border-gray-600 rounded-lg bg-white dark:bg-gray-900 text-gray-900 dark:text-white focus:ring-2 focus:ring-primary-600"
              />
            </div>
          )}
        </div>

        {/* Notifications */}
        <div className="bg-white dark:bg-gray-800 rounded-xl p-6 shadow-sm">
          <h2 className="text-lg font-bold text-gray-900 dark:text-white mb-4 flex items-center gap-2">
            <Bell className="text-primary-600" />
            Reminders
          </h2>
          <div className="space-y-3">
            <label className="flex items-center gap-3 p-3 bg-gray-50 dark:bg-gray-700 rounded-lg cursor-pointer">
              <input
                type="checkbox"
                checked={settings.planReminder}
                onChange={(e) => handleChange('planReminder', e.target.checked)}
                className="w-5 h-5 text-primary-600 rounded focus:ring-2 focus:ring-primary-600"
              />
              <div className="flex-1">
                <p className="font-medium text-gray-900 dark:text-white">Plan Your Week</p>
                <p className="text-sm text-gray-600 dark:text-gray-400">Remind me to plan meals</p>
              </div>
              {settings.planReminder && (
                <input
                  type="time"
                  value={settings.reminderTime}
                  onChange={(e) => handleChange('reminderTime', e.target.value)}
                  className="px-3 py-1 border border-gray-300 dark:border-gray-600 rounded-lg bg-white dark:bg-gray-900 text-gray-900 dark:text-white text-sm"
                />
              )}
            </label>

            <label className="flex items-center gap-3 p-3 bg-gray-50 dark:bg-gray-700 rounded-lg cursor-pointer">
              <input
                type="checkbox"
                checked={settings.shoppingListReminder}
                onChange={(e) => handleChange('shoppingListReminder', e.target.checked)}
                className="w-5 h-5 text-primary-600 rounded focus:ring-2 focus:ring-primary-600"
              />
              <div>
                <p className="font-medium text-gray-900 dark:text-white">Shopping List</p>
                <p className="text-sm text-gray-600 dark:text-gray-400">Remind me to go shopping</p>
              </div>
            </label>

            <label className="flex items-center gap-3 p-3 bg-gray-50 dark:bg-gray-700 rounded-lg cursor-pointer">
              <input
                type="checkbox"
                checked={settings.prepReminder}
                onChange={(e) => handleChange('prepReminder', e.target.checked)}
                className="w-5 h-5 text-primary-600 rounded focus:ring-2 focus:ring-primary-600"
              />
              <div>
                <p className="font-medium text-gray-900 dark:text-white">Meal Prep Day</p>
                <p className="text-sm text-gray-600 dark:text-gray-400">Remind me to prep meals</p>
              </div>
            </label>
          </div>
        </div>

        {/* Save Button */}
        <div className="flex gap-3">
          <button
            onClick={handleSave}
            className="flex-1 px-6 py-3 bg-gradient-to-r from-primary-600 to-primary-700 text-white rounded-xl font-semibold hover:from-primary-700 hover:to-primary-800 transition-all shadow-lg shadow-primary-600/30 flex items-center justify-center gap-2"
          >
            <Save size={20} />
            Save Settings
          </button>
          {saved && (
            <div className="flex items-center gap-2 text-green-600 dark:text-green-400 px-4">
              <Save size={20} />
              <span className="font-medium">Saved!</span>
            </div>
          )}
        </div>
      </div>
    </div>
  )
}

export default MealPlanSettingsPage
